### ISSUE TITLE
As someone interested in Topl, I would like to find up-to-date and well organized information about Topl on their website

### ISSUE THREAD

**Issue by c-georgen** [Topl/Topl_website#3]
Website redesign! We need to update and improve our website

#### Sub-tasks

- [x] Complete map overviewing Topl's activities and uses around the world
- [x] Implement new website layout
- [x] Collect new content for website
- [x] Add new content
